## Charles D. Waters <cwaters8@uw.edu>
## 11/01/2013
## This script takes the haplotype file that was output from Marine's Corrected Genotypes script ("genotypes_verif_v2.py") and then converts the genotypes from a,b,ab,and - to "0101","0202","0102", and "0000"

## Argument 1: Input haplotype file of corrected genotypes, which was generated by Marine's genotypes_verif_v2.py script
## Argument 2: Output file in the genepop format
#python Genepop_conversion_corrected.py batch_2_corrected_genotypes_2_alleles.txt batch_2_corrected_genotypes_2_alleles_genepop.txt
import sys


input_haplotypes=open(sys.argv[1],'r')
output_file_genepop=open(sys.argv[2],'w')

header=True

for line in input_haplotypes:
	if header:
		output_file_genepop.write(line)
		header=False
	else:
		individual=line.split()[0]		
		tmp_line=line			
		tmp_line=tmp_line.replace('-','0000')
		tmp_line=tmp_line.replace('ab','0102')
		tmp_line=tmp_line.replace('a','0101')
		tmp_line=tmp_line.replace('b','0202')
		output_line=str(tmp_line.split()[1:])
		output_line=output_line.replace('[', '').replace(']', '').replace("'", '').replace(',', '\t').replace(' ','').replace('\\n','') + '\n'
		write_line=individual + '\t' + output_line
		output_file_genepop.write(write_line)

output_file_genepop.close()
