
#pstacks
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_035.sam -o ../stacks_b1_wgenome -i 330 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_051.sam -o ../stacks_b1_wgenome -i 331 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_052.sam -o ../stacks_b1_wgenome -i 332 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_053.sam -o ../stacks_b1_wgenome -i 333 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_054.sam -o ../stacks_b1_wgenome -i 334 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_055.sam -o ../stacks_b1_wgenome -i 335 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_056.sam -o ../stacks_b1_wgenome -i 336 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_057.sam -o ../stacks_b1_wgenome -i 337 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_058.sam -o ../stacks_b1_wgenome -i 338 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_059.sam -o ../stacks_b1_wgenome -i 339 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_060.sam -o ../stacks_b1_wgenome -i 340 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_061.sam -o ../stacks_b1_wgenome -i 341 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_062.sam -o ../stacks_b1_wgenome -i 342 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_063.sam -o ../stacks_b1_wgenome -i 343 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_064.sam -o ../stacks_b1_wgenome -i 344 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_065.sam -o ../stacks_b1_wgenome -i 345 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_066.sam -o ../stacks_b1_wgenome -i 346 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_067.sam -o ../stacks_b1_wgenome -i 347 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_068.sam -o ../stacks_b1_wgenome -i 348 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_069.sam -o ../stacks_b1_wgenome -i 349 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_070.sam -o ../stacks_b1_wgenome -i 350 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_071.sam -o ../stacks_b1_wgenome -i 351 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_072.sam -o ../stacks_b1_wgenome -i 352 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_073.sam -o ../stacks_b1_wgenome -i 353 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_074.sam -o ../stacks_b1_wgenome -i 354 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_075.sam -o ../stacks_b1_wgenome -i 355 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_076.sam -o ../stacks_b1_wgenome -i 356 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_077.sam -o ../stacks_b1_wgenome -i 357 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_078.sam -o ../stacks_b1_wgenome -i 358 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_079.sam -o ../stacks_b1_wgenome -i 359 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_080.sam -o ../stacks_b1_wgenome -i 360 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_081.sam -o ../stacks_b1_wgenome -i 361 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_082.sam -o ../stacks_b1_wgenome -i 362 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_083.sam -o ../stacks_b1_wgenome -i 363 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_084.sam -o ../stacks_b1_wgenome -i 364 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_085.sam -o ../stacks_b1_wgenome -i 365 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_086.sam -o ../stacks_b1_wgenome -i 366 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_087.sam -o ../stacks_b1_wgenome -i 367 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_088.sam -o ../stacks_b1_wgenome -i 368 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_089.sam -o ../stacks_b1_wgenome -i 369 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_090.sam -o ../stacks_b1_wgenome -i 370 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_091.sam -o ../stacks_b1_wgenome -i 371 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_092.sam -o ../stacks_b1_wgenome -i 372 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_093.sam -o ../stacks_b1_wgenome -i 373 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_094.sam -o ../stacks_b1_wgenome -i 374 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_095.sam -o ../stacks_b1_wgenome -i 375 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_096.sam -o ../stacks_b1_wgenome -i 376 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/KOD03_097.sam -o ../stacks_b1_wgenome -i 377 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_001.sam -o ../stacks_b1_wgenome -i 378 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_002.sam -o ../stacks_b1_wgenome -i 379 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_003.sam -o ../stacks_b1_wgenome -i 380 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_004.sam -o ../stacks_b1_wgenome -i 381 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_005.sam -o ../stacks_b1_wgenome -i 382 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_006.sam -o ../stacks_b1_wgenome -i 383 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_007.sam -o ../stacks_b1_wgenome -i 384 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_008.sam -o ../stacks_b1_wgenome -i 385 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_009.sam -o ../stacks_b1_wgenome -i 386 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_010.sam -o ../stacks_b1_wgenome -i 387 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_011.sam -o ../stacks_b1_wgenome -i 388 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_012.sam -o ../stacks_b1_wgenome -i 389 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_013.sam -o ../stacks_b1_wgenome -i 390 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_014.sam -o ../stacks_b1_wgenome -i 391 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_015.sam -o ../stacks_b1_wgenome -i 392 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_016.sam -o ../stacks_b1_wgenome -i 393 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_017.sam -o ../stacks_b1_wgenome -i 394 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_018.sam -o ../stacks_b1_wgenome -i 395 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_019.sam -o ../stacks_b1_wgenome -i 396 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_020.sam -o ../stacks_b1_wgenome -i 397 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_021.sam -o ../stacks_b1_wgenome -i 398 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_022.sam -o ../stacks_b1_wgenome -i 399 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_023.sam -o ../stacks_b1_wgenome -i 400 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_024.sam -o ../stacks_b1_wgenome -i 401 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_025.sam -o ../stacks_b1_wgenome -i 402 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_026.sam -o ../stacks_b1_wgenome -i 403 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_027.sam -o ../stacks_b1_wgenome -i 404 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_028.sam -o ../stacks_b1_wgenome -i 405 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_029.sam -o ../stacks_b1_wgenome -i 406 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_030.sam -o ../stacks_b1_wgenome -i 407 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_031.sam -o ../stacks_b1_wgenome -i 408 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_032.sam -o ../stacks_b1_wgenome -i 409 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_033.sam -o ../stacks_b1_wgenome -i 410 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_034.sam -o ../stacks_b1_wgenome -i 411 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_035.sam -o ../stacks_b1_wgenome -i 412 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_036.sam -o ../stacks_b1_wgenome -i 413 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_037.sam -o ../stacks_b1_wgenome -i 414 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_038.sam -o ../stacks_b1_wgenome -i 415 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_039.sam -o ../stacks_b1_wgenome -i 416 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_040.sam -o ../stacks_b1_wgenome -i 417 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_041.sam -o ../stacks_b1_wgenome -i 418 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_042.sam -o ../stacks_b1_wgenome -i 419 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_043.sam -o ../stacks_b1_wgenome -i 420 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_044.sam -o ../stacks_b1_wgenome -i 421 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_045.sam -o ../stacks_b1_wgenome -i 422 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_046.sam -o ../stacks_b1_wgenome -i 423 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_047.sam -o ../stacks_b1_wgenome -i 424 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/AD06_048.sam -o ../stacks_b1_wgenome -i 425 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_001.sam -o ../stacks_b1_wgenome -i 426 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_002.sam -o ../stacks_b1_wgenome -i 427 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_003.sam -o ../stacks_b1_wgenome -i 428 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_004.sam -o ../stacks_b1_wgenome -i 429 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_005.sam -o ../stacks_b1_wgenome -i 430 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_006.sam -o ../stacks_b1_wgenome -i 431 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_007.sam -o ../stacks_b1_wgenome -i 432 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_008.sam -o ../stacks_b1_wgenome -i 433 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_009.sam -o ../stacks_b1_wgenome -i 434 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_010.sam -o ../stacks_b1_wgenome -i 435 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_011.sam -o ../stacks_b1_wgenome -i 436 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_012.sam -o ../stacks_b1_wgenome -i 437 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_013.sam -o ../stacks_b1_wgenome -i 438 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_014.sam -o ../stacks_b1_wgenome -i 439 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_015.sam -o ../stacks_b1_wgenome -i 440 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_016.sam -o ../stacks_b1_wgenome -i 441 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_017.sam -o ../stacks_b1_wgenome -i 442 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_018.sam -o ../stacks_b1_wgenome -i 443 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_019.sam -o ../stacks_b1_wgenome -i 444 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_020.sam -o ../stacks_b1_wgenome -i 445 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_021.sam -o ../stacks_b1_wgenome -i 446 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_022.sam -o ../stacks_b1_wgenome -i 447 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_023.sam -o ../stacks_b1_wgenome -i 448 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_024.sam -o ../stacks_b1_wgenome -i 449 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_025.sam -o ../stacks_b1_wgenome -i 450 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_026.sam -o ../stacks_b1_wgenome -i 451 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_027.sam -o ../stacks_b1_wgenome -i 452 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_028.sam -o ../stacks_b1_wgenome -i 453 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_029.sam -o ../stacks_b1_wgenome -i 454 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_030.sam -o ../stacks_b1_wgenome -i 455 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_031.sam -o ../stacks_b1_wgenome -i 456 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_032.sam -o ../stacks_b1_wgenome -i 457 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_033.sam -o ../stacks_b1_wgenome -i 458 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_034.sam -o ../stacks_b1_wgenome -i 459 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_035.sam -o ../stacks_b1_wgenome -i 460 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_036.sam -o ../stacks_b1_wgenome -i 461 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_037.sam -o ../stacks_b1_wgenome -i 462 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_038.sam -o ../stacks_b1_wgenome -i 463 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_039.sam -o ../stacks_b1_wgenome -i 464 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_040.sam -o ../stacks_b1_wgenome -i 465 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_041.sam -o ../stacks_b1_wgenome -i 466 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_042.sam -o ../stacks_b1_wgenome -i 467 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_043.sam -o ../stacks_b1_wgenome -i 468 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_044.sam -o ../stacks_b1_wgenome -i 469 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_045.sam -o ../stacks_b1_wgenome -i 470 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_046.sam -o ../stacks_b1_wgenome -i 471 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_047.sam -o ../stacks_b1_wgenome -i 472 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/WC05_048.sam -o ../stacks_b1_wgenome -i 473 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_001.sam -o ../stacks_b1_wgenome -i 474 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_002.sam -o ../stacks_b1_wgenome -i 475 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_003.sam -o ../stacks_b1_wgenome -i 476 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_004.sam -o ../stacks_b1_wgenome -i 477 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_005.sam -o ../stacks_b1_wgenome -i 478 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_006.sam -o ../stacks_b1_wgenome -i 479 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_007.sam -o ../stacks_b1_wgenome -i 480 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_008.sam -o ../stacks_b1_wgenome -i 481 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_009.sam -o ../stacks_b1_wgenome -i 482 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_010.sam -o ../stacks_b1_wgenome -i 483 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_011.sam -o ../stacks_b1_wgenome -i 484 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_012.sam -o ../stacks_b1_wgenome -i 485 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_013.sam -o ../stacks_b1_wgenome -i 486 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_014.sam -o ../stacks_b1_wgenome -i 487 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_015.sam -o ../stacks_b1_wgenome -i 488 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_016.sam -o ../stacks_b1_wgenome -i 489 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_017.sam -o ../stacks_b1_wgenome -i 490 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_018.sam -o ../stacks_b1_wgenome -i 491 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_019.sam -o ../stacks_b1_wgenome -i 492 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_020.sam -o ../stacks_b1_wgenome -i 493 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_021.sam -o ../stacks_b1_wgenome -i 494 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_022.sam -o ../stacks_b1_wgenome -i 495 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_023.sam -o ../stacks_b1_wgenome -i 496 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_024.sam -o ../stacks_b1_wgenome -i 497 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_025.sam -o ../stacks_b1_wgenome -i 498 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_026.sam -o ../stacks_b1_wgenome -i 499 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_027.sam -o ../stacks_b1_wgenome -i 500 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_028.sam -o ../stacks_b1_wgenome -i 501 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_029.sam -o ../stacks_b1_wgenome -i 502 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_030.sam -o ../stacks_b1_wgenome -i 503 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_031.sam -o ../stacks_b1_wgenome -i 504 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_032.sam -o ../stacks_b1_wgenome -i 505 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_033.sam -o ../stacks_b1_wgenome -i 506 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_034.sam -o ../stacks_b1_wgenome -i 507 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_035.sam -o ../stacks_b1_wgenome -i 508 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_036.sam -o ../stacks_b1_wgenome -i 509 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_037.sam -o ../stacks_b1_wgenome -i 510 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_038.sam -o ../stacks_b1_wgenome -i 511 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_039.sam -o ../stacks_b1_wgenome -i 512 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_040.sam -o ../stacks_b1_wgenome -i 513 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_041.sam -o ../stacks_b1_wgenome -i 514 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_042.sam -o ../stacks_b1_wgenome -i 515 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_043.sam -o ../stacks_b1_wgenome -i 516 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_044.sam -o ../stacks_b1_wgenome -i 517 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_045.sam -o ../stacks_b1_wgenome -i 518 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_046.sam -o ../stacks_b1_wgenome -i 519 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_047.sam -o ../stacks_b1_wgenome -i 520 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/HS04_048.sam -o ../stacks_b1_wgenome -i 521 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_001.sam -o ../stacks_b1_wgenome -i 522 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_002.sam -o ../stacks_b1_wgenome -i 523 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_003.sam -o ../stacks_b1_wgenome -i 524 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_004.sam -o ../stacks_b1_wgenome -i 525 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_005.sam -o ../stacks_b1_wgenome -i 526 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_006.sam -o ../stacks_b1_wgenome -i 527 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_007.sam -o ../stacks_b1_wgenome -i 528 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_008.sam -o ../stacks_b1_wgenome -i 529 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_009.sam -o ../stacks_b1_wgenome -i 530 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_010.sam -o ../stacks_b1_wgenome -i 531 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_011.sam -o ../stacks_b1_wgenome -i 532 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_012.sam -o ../stacks_b1_wgenome -i 533 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_013.sam -o ../stacks_b1_wgenome -i 534 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_014.sam -o ../stacks_b1_wgenome -i 535 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_015.sam -o ../stacks_b1_wgenome -i 536 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_016.sam -o ../stacks_b1_wgenome -i 537 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_017.sam -o ../stacks_b1_wgenome -i 538 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_018.sam -o ../stacks_b1_wgenome -i 539 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_019.sam -o ../stacks_b1_wgenome -i 540 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_020.sam -o ../stacks_b1_wgenome -i 541 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_021.sam -o ../stacks_b1_wgenome -i 542 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_022.sam -o ../stacks_b1_wgenome -i 543 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_023.sam -o ../stacks_b1_wgenome -i 544 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_024.sam -o ../stacks_b1_wgenome -i 545 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_025.sam -o ../stacks_b1_wgenome -i 546 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_026.sam -o ../stacks_b1_wgenome -i 547 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_027.sam -o ../stacks_b1_wgenome -i 548 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_028.sam -o ../stacks_b1_wgenome -i 549 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_029.sam -o ../stacks_b1_wgenome -i 550 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_030.sam -o ../stacks_b1_wgenome -i 551 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_031.sam -o ../stacks_b1_wgenome -i 552 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_032.sam -o ../stacks_b1_wgenome -i 553 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_033.sam -o ../stacks_b1_wgenome -i 554 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_034.sam -o ../stacks_b1_wgenome -i 555 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_035.sam -o ../stacks_b1_wgenome -i 556 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_036.sam -o ../stacks_b1_wgenome -i 557 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_037.sam -o ../stacks_b1_wgenome -i 558 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_038.sam -o ../stacks_b1_wgenome -i 559 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_039.sam -o ../stacks_b1_wgenome -i 560 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_040.sam -o ../stacks_b1_wgenome -i 561 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_041.sam -o ../stacks_b1_wgenome -i 562 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_042.sam -o ../stacks_b1_wgenome -i 563 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_043.sam -o ../stacks_b1_wgenome -i 564 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_044.sam -o ../stacks_b1_wgenome -i 565 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_045.sam -o ../stacks_b1_wgenome -i 566 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_046.sam -o ../stacks_b1_wgenome -i 567 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_047.sam -o ../stacks_b1_wgenome -i 568 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PI04_048.sam -o ../stacks_b1_wgenome -i 569 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_008.sam -o ../stacks_b1_wgenome -i 570 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_048.sam -o ../stacks_b1_wgenome -i 571 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_031.sam -o ../stacks_b1_wgenome -i 572 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_036.sam -o ../stacks_b1_wgenome -i 573 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_030.sam -o ../stacks_b1_wgenome -i 574 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_006.sam -o ../stacks_b1_wgenome -i 575 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_016.sam -o ../stacks_b1_wgenome -i 576 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_033.sam -o ../stacks_b1_wgenome -i 577 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_015.sam -o ../stacks_b1_wgenome -i 578 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_014.sam -o ../stacks_b1_wgenome -i 579 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_044.sam -o ../stacks_b1_wgenome -i 580 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_037.sam -o ../stacks_b1_wgenome -i 581 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_004.sam -o ../stacks_b1_wgenome -i 582 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_040.sam -o ../stacks_b1_wgenome -i 583 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_023.sam -o ../stacks_b1_wgenome -i 584 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_042.sam -o ../stacks_b1_wgenome -i 585 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_024.sam -o ../stacks_b1_wgenome -i 586 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_034.sam -o ../stacks_b1_wgenome -i 587 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_003.sam -o ../stacks_b1_wgenome -i 588 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_002.sam -o ../stacks_b1_wgenome -i 589 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_001.sam -o ../stacks_b1_wgenome -i 590 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_041.sam -o ../stacks_b1_wgenome -i 591 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_013.sam -o ../stacks_b1_wgenome -i 592 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_027.sam -o ../stacks_b1_wgenome -i 593 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_039.sam -o ../stacks_b1_wgenome -i 594 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_020.sam -o ../stacks_b1_wgenome -i 595 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_012.sam -o ../stacks_b1_wgenome -i 596 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_029.sam -o ../stacks_b1_wgenome -i 597 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_022.sam -o ../stacks_b1_wgenome -i 598 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_007.sam -o ../stacks_b1_wgenome -i 599 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_046.sam -o ../stacks_b1_wgenome -i 600 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_043.sam -o ../stacks_b1_wgenome -i 601 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_045.sam -o ../stacks_b1_wgenome -i 602 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_011.sam -o ../stacks_b1_wgenome -i 603 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_028.sam -o ../stacks_b1_wgenome -i 604 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_021.sam -o ../stacks_b1_wgenome -i 605 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_026.sam -o ../stacks_b1_wgenome -i 606 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_010.sam -o ../stacks_b1_wgenome -i 607 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_025.sam -o ../stacks_b1_wgenome -i 608 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_019.sam -o ../stacks_b1_wgenome -i 609 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_038.sam -o ../stacks_b1_wgenome -i 610 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_017.sam -o ../stacks_b1_wgenome -i 611 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_047.sam -o ../stacks_b1_wgenome -i 612 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_032.sam -o ../stacks_b1_wgenome -i 613 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_018.sam -o ../stacks_b1_wgenome -i 614 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_035.sam -o ../stacks_b1_wgenome -i 615 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_005.sam -o ../stacks_b1_wgenome -i 616 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PS12_009.sam -o ../stacks_b1_wgenome -i 617 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_001.sam -o ../stacks_b1_wgenome -i 618 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_002.sam -o ../stacks_b1_wgenome -i 619 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_003.sam -o ../stacks_b1_wgenome -i 620 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_004.sam -o ../stacks_b1_wgenome -i 621 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_005.sam -o ../stacks_b1_wgenome -i 622 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_006.sam -o ../stacks_b1_wgenome -i 623 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_007.sam -o ../stacks_b1_wgenome -i 624 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_008.sam -o ../stacks_b1_wgenome -i 625 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_009.sam -o ../stacks_b1_wgenome -i 626 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_010.sam -o ../stacks_b1_wgenome -i 627 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_011.sam -o ../stacks_b1_wgenome -i 628 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_012.sam -o ../stacks_b1_wgenome -i 629 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_013.sam -o ../stacks_b1_wgenome -i 630 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_014.sam -o ../stacks_b1_wgenome -i 631 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_015.sam -o ../stacks_b1_wgenome -i 632 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_016.sam -o ../stacks_b1_wgenome -i 633 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/GS13_017.sam -o ../stacks_b1_wgenome -i 634 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_002.sam -o ../stacks_b1_wgenome -i 635 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_003.sam -o ../stacks_b1_wgenome -i 636 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_005.sam -o ../stacks_b1_wgenome -i 637 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_006.sam -o ../stacks_b1_wgenome -i 638 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_009.sam -o ../stacks_b1_wgenome -i 639 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_010.sam -o ../stacks_b1_wgenome -i 640 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_011.sam -o ../stacks_b1_wgenome -i 641 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_014.sam -o ../stacks_b1_wgenome -i 642 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_015.sam -o ../stacks_b1_wgenome -i 643 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_016.sam -o ../stacks_b1_wgenome -i 644 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_017.sam -o ../stacks_b1_wgenome -i 645 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_018.sam -o ../stacks_b1_wgenome -i 646 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_021.sam -o ../stacks_b1_wgenome -i 647 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_022.sam -o ../stacks_b1_wgenome -i 648 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_023.sam -o ../stacks_b1_wgenome -i 649 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_063.sam -o ../stacks_b1_wgenome -i 650 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_075.sam -o ../stacks_b1_wgenome -i 651 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_079.sam -o ../stacks_b1_wgenome -i 652 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_094.sam -o ../stacks_b1_wgenome -i 653 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_095.sam -o ../stacks_b1_wgenome -i 654 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_096.sam -o ../stacks_b1_wgenome -i 655 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_097.sam -o ../stacks_b1_wgenome -i 656 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_131.sam -o ../stacks_b1_wgenome -i 657 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/PWS12_133.sam -o ../stacks_b1_wgenome -i 658 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_001.sam -o ../stacks_b1_wgenome -i 659 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_009.sam -o ../stacks_b1_wgenome -i 660 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_017.sam -o ../stacks_b1_wgenome -i 661 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_025.sam -o ../stacks_b1_wgenome -i 662 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_033.sam -o ../stacks_b1_wgenome -i 663 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_041.sam -o ../stacks_b1_wgenome -i 664 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_002.sam -o ../stacks_b1_wgenome -i 665 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_010.sam -o ../stacks_b1_wgenome -i 666 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_018.sam -o ../stacks_b1_wgenome -i 667 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_026.sam -o ../stacks_b1_wgenome -i 668 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_034.sam -o ../stacks_b1_wgenome -i 669 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_042.sam -o ../stacks_b1_wgenome -i 670 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_003.sam -o ../stacks_b1_wgenome -i 671 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_011.sam -o ../stacks_b1_wgenome -i 672 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_019.sam -o ../stacks_b1_wgenome -i 673 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_027.sam -o ../stacks_b1_wgenome -i 674 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_035.sam -o ../stacks_b1_wgenome -i 675 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_043.sam -o ../stacks_b1_wgenome -i 676 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_004.sam -o ../stacks_b1_wgenome -i 677 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_012.sam -o ../stacks_b1_wgenome -i 678 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_020.sam -o ../stacks_b1_wgenome -i 679 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_028.sam -o ../stacks_b1_wgenome -i 680 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_036.sam -o ../stacks_b1_wgenome -i 681 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_044.sam -o ../stacks_b1_wgenome -i 682 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_005.sam -o ../stacks_b1_wgenome -i 683 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_013.sam -o ../stacks_b1_wgenome -i 684 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_021.sam -o ../stacks_b1_wgenome -i 685 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_029.sam -o ../stacks_b1_wgenome -i 686 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_037.sam -o ../stacks_b1_wgenome -i 687 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_045.sam -o ../stacks_b1_wgenome -i 688 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_006.sam -o ../stacks_b1_wgenome -i 689 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_014.sam -o ../stacks_b1_wgenome -i 690 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_022.sam -o ../stacks_b1_wgenome -i 691 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_030.sam -o ../stacks_b1_wgenome -i 692 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_038.sam -o ../stacks_b1_wgenome -i 693 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_046.sam -o ../stacks_b1_wgenome -i 694 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_007.sam -o ../stacks_b1_wgenome -i 695 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_015.sam -o ../stacks_b1_wgenome -i 696 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_023.sam -o ../stacks_b1_wgenome -i 697 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_031.sam -o ../stacks_b1_wgenome -i 698 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_039.sam -o ../stacks_b1_wgenome -i 699 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_047.sam -o ../stacks_b1_wgenome -i 700 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_008.sam -o ../stacks_b1_wgenome -i 701 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_016.sam -o ../stacks_b1_wgenome -i 702 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_024.sam -o ../stacks_b1_wgenome -i 703 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_032.sam -o ../stacks_b1_wgenome -i 704 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_040.sam -o ../stacks_b1_wgenome -i 705 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
pstacks -t sam -f ../stacks_b1_wgenome/UP03_048.sam -o ../stacks_b1_wgenome -i 706 -m 10 -p 6 --model_type bounded 2>> ../stacks_b1_wgenome/pstacks_out_b1_wgenome
